export const LOAD_DISHES = "LOAD_DISHES";
export const ADD_TO_FAVOURITES = "ADD_TO_FAVOURITES";
export const REMOVE_FAVOURITES = "REMOVE_FAVOURITES";

export const TRY_SIGNUP = 'TRY_SIGNUP';
export const TRY_LOGIN = 'TRY_LOGIN';